name: xcodebuild

on:
  push:
    tags:
      - 'v*' 
jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - name: Bundler & CocoaPods
      run: |
        gem install bundler
        bundle install
    - name: Start CI
      run: bundle exec fastlane startCI
    
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
        export LIB_VERSION=${VERSION:1}
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
